name: scmalignant
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=25.0=py310h06a4308_1
  - pip=26.0.1=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.10=h7a1cb2a_2
  - readline=8.3=hc2a1206_0
  - setuptools=80.10.2=py310h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.46.3=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - aiobotocore==3.1.3
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aioitertools==0.13.0
      - aiosignal==1.4.0
      - anndata==0.9.1
      - arboreto==0.1.6
      - asciitree==0.3.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bokeh==3.8.2
      - boltons==25.0.0
      - botocore==1.42.49
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorcet==3.1.0
      - contourpy==1.3.2
      - ctxcore==0.2.0
      - cycler==0.12.1
      - cytoolz==1.1.0
      - dask==2024.11.2
      - dask-expr==1.1.19
      - dask-image==2025.11.0
      - datashader==0.18.2
      - dill==0.4.1
      - distributed==2024.11.2
      - docrep==0.3.2
      - fasteners==0.20
      - fonttools==4.61.1
      - frozendict==2.4.7
      - frozenlist==1.8.0
      - fsspec==2026.2.0
      - geopandas==1.1.2
      - h5py==3.7.0
      - idna==3.11
      - igraph==1.0.0
      - imageio==2.37.2
      - importlib-metadata==8.7.1
      - inflect==7.5.0
      - interlap==0.2.7
      - jinja2==3.1.6
      - jmespath==1.1.0
      - joblib==1.4.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - leidenalg==0.11.0
      - llvmlite==0.46.0
      - locket==1.0.0
      - loompy==3.0.8
      - lz4==4.4.5
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.6.3
      - matplotlib-scalebar==0.9.0
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - msgpack==1.1.2
      - multidict==6.7.1
      - multipledispatch==1.0.0
      - multiprocessing-on-dill==3.5.0a4
      - multiscale-spatial-image==2.0.2
      - narwhals==2.16.0
      - natsort==8.4.0
      - networkx==3.4.2
      - numba==0.64.0
      - numcodecs==0.13.1
      - numexpr==2.14.1
      - numpy==1.26.4
      - numpy-groupies==0.11.3
      - ome-zarr==0.11.1
      - omnipath==1.0.12
      - pandas==2.1.4
      - param==2.3.2
      - partd==1.4.2
      - patsy==1.0.2
      - pillow==12.1.1
      - pims==0.7
      - platformdirs==4.9.2
      - pooch==1.9.0
      - propcache==0.4.1
      - psutil==7.2.2
      - pyarrow==23.0.1
      - pyct==0.6.0
      - pygments==2.19.2
      - pynndescent==0.6.0
      - pyogrio==0.12.1
      - pyparsing==3.3.2
      - pyproj==3.7.1
      - pyscenic==0.12.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.3.3
      - s3fs==2026.2.0
      - scanpy==1.9.3
      - scikit-image==0.20.0
      - scikit-learn==1.2.2
      - scipy==1.13.1
      - scmalignantfinder==1.1.8
      - seaborn==0.13.2
      - session-info==1.0.1
      - shapely==2.1.2
      - six==1.17.0
      - slicerator==1.1.0
      - sortedcontainers==2.4.0
      - spatial-image==1.2.1
      - spatialdata==0.4.0
      - squidpy==1.3.1
      - statsmodels==0.14.6
      - stdlib-list==0.12.0
      - tblib==3.2.2
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - toolz==1.1.0
      - tornado==6.5.4
      - tqdm==4.67.3
      - typeguard==4.5.1
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - umap-learn==0.5.7
      - urllib3==2.6.3
      - validators==0.35.0
      - wrapt==2.1.1
      - xarray==2024.11.0
      - xarray-dataclasses==1.9.1
      - xarray-schema==0.0.3
      - xarray-spatial==0.5.2
      - xyzservices==2025.11.0
      - yarl==1.22.0
      - zarr==2.18.3
      - zict==3.0.0
      - zipp==3.23.0
